### ISSUE TITLE
Student sign in

### ISSUE THREAD

**Issue by tadas-s** [jerryluk/omniauth-edmodo#1]
When user signing in is a student, then profile response from `/users/me` is:

```
{
     "url" => "https://api.edmodo.com/users/74201543",
      "id" => 74201543,
    "type" => "student"
}
```

Because of this, [the following code](https://github.com/jerryluk/omniauth-edmodo/blob/master/lib/omniauth/strategies/edmodo.rb#L34) throws an exception:

```
        {
          'nickname' => raw_info['username'],
          'email' => raw_info['email'],
          'first_name' => raw_info['first_name'],
          'last_name' => raw_info['last_name'],
          'image' => raw_info['avatars']['large']
        }
```

(edmodo.rb, line 34 to be specific)

With this response `raw_info['avatars']` is nil, so `nil['large']` raises:

```
NoMethodError: undefined method `[]' for nil:NilClass
```

Kind of easy fix but we're not entirely sure if it's a valid student profile in the first place.

**Comment by tadas-s** [comment]
Oh, also: colleague mentioned that this also failed with a teacher account until he uploaded his avatar image.

**Comment by redroot** [comment]
+1
